title: Today's dinner
author: Ayumaru
email: b0117180f3@edu.teu.ac.jp
description: > # this means to ignore newlines until "baseurl:"
  今日の晩御飯はパスタ食べたい。

# social links
twitter_username: @ayu_eightlove # DO NOT include the @ character, or else the build will fail!
github_username:  Ayumaru # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
